/**
 * Created by sina on 2016/6/27.
 */
module.exports = {
    subDir: [
        {
            dirName: 'pages',
            subDir: [
                {
                    dirName:'css',
                    subDir:[]
                },
                {
                    dirName:'html',
                    subDir:[]
                },
                {
                    dirName:'img',
                    subDir:[]
                },
                {
                    dirName:'js',
                    subDir:[
                        {
                            dirName:'lib',
                            subDir:[
                                {
                                    dirName:'core',
                                    subDir:[]
                                },
                                {
                                    dirName:'kit',
                                    subDir:[
                                        {
                                            dirName:'util',
                                            subDir:[]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            dirName:'mods',
                            subDir:[
                                {
                                    dirName:'common',
                                    subDir:[]
                                },
                                {
                                    dirName:'conf',
                                    subDir:[]
                                },
                                {
                                    dirName:'data',
                                    subDir:[]
                                },
                                {
                                    dirName:'ui',
                                    subDir:[]
                                }
                            ]
                        },
                        {
                            dirName:'page',
                            subDir:[]
                        }
                    ]
                }
            ]
        },{
            dirName:'server',
            subDir:[]
        }
    ]
};
